name: Async TCP CI

on:
  push:
    branches:
  pull_request:

jobs:
  compile_sketch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fqbn:
          - esp32:esp32:esp32
          - esp32:esp32:esp32s3
          - esp32:esp32:esp32c3
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}
          platforms: |
            - name: esp32:esp32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          sketch-paths: |
            - examples/ClientServer/Server
